@zaitsev firstCommit
yamnyk/trigger-agency-landing pull request #15
Opened 2019-04-17 15:55 UTC by Zaitsev-Aleksandr

add-advantage-section

2019-04-19 21:16 UTC, yamnyk commented on src/scss/all.scss
> +@import "slider/slick";
этого файла нет в ветке. локально может у тебя он и есть, но у меня в стянутой ветке его не существует и билд не собирается

2019-04-19 21:20 UTC, yamnyk requested changes
со скриптом ты натупил скорее всего с порядком. я проверить никак не могу пока не заработает слайдер. 
Порефакторю что смогу сам, но в понедельник будь как штык, будем разбираться и учить тебя работать в команде, бо дальше так не пойдет. Есть коллектив, есть задача, есть алгоритм последовательный по которому работают ВСЕ и ОСОБЕННО ТЫ. 
Нарушаешь алгоритм общей работы - получаем овертайм на 6 если не больше часов. Теперь еще один овертайм будет на то чтобы отладить все то что ты прислал. Это не ок. 

И еще. Конфликты с мастером решать должен ТЫ. И решать их нужно ПЕРЕД тем как отправить коммит на ветку. КАЖДЫЙ РАЗ мердждишь удаленный мастер в совю ветку, разбираешься чтобы все работало и ТОКЛЬКО ПОСЛЕ ЭТОГО пушишь в репозиторий. Короче я в понедельник будем работать над этим.

Разработчик ты хороший, но не дисциплинированный ничерта.

2019-04-19 21:20 UTC, yamnyk commented on src/scss/all.scss
> +@import "slider/slick-theme";
этого файла нет в ветке. локально может у тебя он и есть, но у меня в стянутой ветке его не существует и билд не собирается

2019-04-24 09:52 UTC, yamnyk approved these changes

2019-04-24 09:55 UTC, denvradiy approved these changes

2019-04-24 10:00 UTC, Rostik3 approved these changes

2019-04-24 10:01 UTC, merged