Adaptive header
yamnyk/trigger-agency-landing pull request #23
Opened 2019-04-30 09:56 UTC by Rostik3

2019-04-30 10:46 UTC, yamnyk commented on src/scss/media/_001_header-media.scss
>            transform-origin: -2.5px 1px;
исправить на  rem-ы

2019-04-30 10:47 UTC, yamnyk requested changes

2019-04-30 10:47 UTC, yamnyk commented on src/scss/media/_001_header-media.scss
>          border-bottom: 1px solid #b4b4b4;
исправить на  rem-ы

2019-04-30 10:47 UTC, yamnyk commented on src/scss/media/_001_header-media.scss
>            height: 2px;
исправить на  rem-ы

2019-05-01 19:45 UTC, yamnyk approved these changes

2019-05-01 19:46 UTC, hliadchyshyn approved these changes

2019-05-01 20:28 UTC, merged