add order section
yamnyk/trigger-agency-landing pull request #6
Opened 2019-04-13 10:59 UTC by denvradiy

2019-04-13 11:42 UTC, Rostik3 submitted a review, later dismissed

2019-04-15 13:10 UTC, yamnyk commented on src/scss/sections/_order.scss
> +    padding-bottom: 4.8rem;
воздух вокруг елемента должен быть воздухом, а не внутренним отступом. Вспоминаем разницу между padding и margin

2019-04-15 13:14 UTC, yamnyk commented on src/scss/sections/_order.scss
> +.container-for-flex{
**ИМЕНИВАНИЕ КЛАССОВ!!!!!**
+ разобраться с высотой. Она должна быть в одном месте. Либо у секции(что плоховато, т.к. при добавлении в нее контента всему настанут лапти), либо у конкретного елемента (уже лучше, но все равно не айс), либо ни у кого(идеальный вариант).

2019-04-15 13:16 UTC, yamnyk commented on src/scss/sections/_order.scss
> +      height: 5.5rem;
размеры кнопке лучше задавать внутренними отступами. Для того, чтобы ее размеры никак не привязывались к количеству текста.

2019-04-15 13:17 UTC, yamnyk requested changes
Переделай все что откомментил и заапрувим.

2019-04-16 18:23 UTC, yamnyk commented on src/index.html
> +    <div class="container container-info-form-wrapper">
ВНИМАНИЕ - избыточная вложенность *detected*!!
давай завязывай с этим. Вполне можно обойтись без этого дивака перекинув свойства этого класса в другой.

2019-04-16 18:24 UTC, yamnyk commented on src/scss/sections/_order.scss
> +    line-height: 2.7rem;
юзай лучше просто полуторный отступ. Тупо пишешь `1.5` и все будет чики-бумбони

2019-04-16 18:27 UTC, yamnyk requested changes
мелкие изменения внеси и завтра тебя смерджим, будешь делать адаптив

2019-04-17 10:20 UTC, yamnyk approved these changes

2019-04-17 10:24 UTC, Rostik3 approved these changes

2019-04-17 10:24 UTC, merged