adding simple structure of items-section
yamnyk/trigger-agency-landing pull request #7
Opened 2019-04-13 11:08 UTC by kor1k

2019-04-13 11:42 UTC, Rostik3 submitted a review, later dismissed

2019-04-14 14:12 UTC, yamnyk commented on src/scss/sections/_team.scss
> +//.services-title::after {
если код закоментирован то его либо не должно быть, либо надо доработать и потом просить ревью))))

2019-04-14 14:13 UTC, yamnyk commented on src/scss/sections/_team.scss
> +.team-description-bonus > span {
мы не используем селектор наследования. Потому что потом если вдруг надо будет стучаться к елементу через скрипт, то для присвоения стилей может понадобиться искусственно наращивать вес - это очень плохо и неудобно!
По этому плз верстай по принципу - У КАЖДОГО ЭЛЕМЕНТА ЕСТЬ КЛАСС

2019-04-14 14:14 UTC, yamnyk commented on src/scss/sections/_team.scss
> +  //display: flex;
Повторяюсь) Любо удаляй комменты перед пушем, либо исправляй и чтоб работало))

2019-04-14 14:15 UTC, yamnyk commented on src/scss/sections/_team.scss
> +  //display: flex;
и здесь тоже комменты оставил))
Мы конечно можем наконфижить чтобы при сборке они отваливались автоматом, но это не освобождает никого от ответственности за собственный код.

2019-04-14 14:16 UTC, yamnyk requested changes
В целом курс движения понятен))
Используй только классы для стилизации, закомментированного кода не должно быть.

Допиливай чтобы выглядело как на макете)

2019-04-14 18:04 UTC, kor1k commented on src/scss/sections/_team.scss
> +//.services-title::after {
ты же сам знаешь, что код ещё далеко не готов для полного деплоя / ревью и он будет рефакториться ещё 200 раз))))

2019-04-14 18:05 UTC, kor1k commented on src/scss/sections/_team.scss
> +.team-description-bonus > span {
добро, я знаю. это было сделано на скорую руку

2019-04-14 18:05 UTC, kor1k commented on src/scss/sections/_team.scss
> +  //display: flex;
ты же сам знаешь, что код ещё далеко не готов для полного деплоя / ревью и он будет рефакториться ещё 200 раз))))

2019-04-14 18:05 UTC, kor1k commented on src/scss/sections/_team.scss
> +  //display: flex;
ты же сам знаешь, что код ещё далеко не готов для полного деплоя / ревью и он будет рефакториться ещё 200 раз))))

2019-04-16 17:46 UTC, yamnyk commented on src/scss/sections/_team.scss
> +.services-item > p {
ну йоп....

2019-04-16 17:47 UTC, yamnyk commented on src/scss/sections/_team.scss
> +.team-description-subtitle {
юзай SCSS.
если не помнишь что это такое и как юзать - не стесняйся придолбись ко мне или к Зайцеву. Тебе будет удобнее писать. Именование классов нормальное, только надо перефигачить на БЕМ.

2019-04-16 17:47 UTC, yamnyk commented on src/scss/sections/_team.scss
> +  font-family: Releway, sans-serif;
если работает то ок, но везде я писал 'Releway' в ковычках.

2019-04-16 17:49 UTC, yamnyk commented on src/index.html
>  <section class="team">
запихни секцию в контейнер!!!

2019-04-16 17:50 UTC, yamnyk commented on src/index.html
> +        <div class="team-description-content">
выплюни и выкинь этот дивак. Он не нужен, тем более что на нем одна пропертя валяется только))

2019-04-16 17:52 UTC, yamnyk commented on src/scss/sections/_team.scss
> +  padding: 0.5rem 2rem 0.5rem 22rem;
мы договорились что градиент на заголовках секции это псевдоелемент, который абсолютом вылазит за пределы контейнера.

2019-04-16 17:53 UTC, yamnyk commented on src/scss/sections/_team.scss
> +  margin: 12rem 0 4rem 0;
зарежу блин! 
без контейнера эта схема работает, но все равно костыль. По этому сделай по-людски. сверстай нормально флексами чтоли эту часть описания команды.

2019-04-16 17:55 UTC, yamnyk commented on src/index.html
> +        <div class="team-description-content">
зачем этот класс есть, и почему он занимает ВСЕ место секции по не, когда должен занимать половину?

2019-04-16 17:58 UTC, yamnyk commented on src/scss/sections/_team.scss
> +  position: relative;
Эдди при наличии контейнера будет обрезаться. Нужно либо релейтив дать родителю более высокого порядка, либо покрутить с абсолютами...может этому классу дать абсолют и сместить его..это конечно костыль дикий и юзать его только в крайней необходимости.

2019-04-16 17:58 UTC, yamnyk commented on src/scss/sections/_team.scss
> +.cubic-1,
блядь. серьезно?!

2019-04-16 18:00 UTC, yamnyk requested changes
Секция с услугами в целом ок. Описание команды - надо поправить, часть надо будет норм переделать так и покумекать как отобразить нормально.

Подходи завтра 17.04.2019 ко мне...я с 11 буду

2019-04-17 12:27 UTC, kor1k commented on src/scss/sections/_team.scss
> +.cubic-1,
изменил на hexagon

2019-04-17 12:29 UTC, kor1k commented on src/index.html
>  <section class="team">
закинул

2019-04-17 12:29 UTC, kor1k commented on src/scss/sections/_team.scss
> +  font-family: Releway, sans-serif;
работает и так. надо изменять?

2019-04-17 12:32 UTC, kor1k commented on src/scss/sections/_team.scss
> +.services-item > p {
забыл. уже сделал

2019-04-17 12:32 UTC, kor1k commented on src/index.html
> +        <div class="team-description-content">
это обёртка

2019-04-17 12:50 UTC, kor1k commented on src/scss/sections/_team.scss
> +  position: relative;
вроде теперь норм

2019-04-22 08:53 UTC, yamnyk approved these changes
есть что еще фиксить, но мерджим потому что жмет отправить сайт на хост хоть в каком-то виде

2019-04-22 08:55 UTC, denvradiy approved these changes

2019-04-22 08:56 UTC, merged