add contacts template
yamnyk/trigger-agency-landing pull request #8
Opened 2019-04-13 11:41 UTC by Rostik3

2019-04-13 16:52 UTC, denvradiy submitted a review, later dismissed

2019-04-16 18:08 UTC, yamnyk commented on src/scss/sections/_footer.scss
> +      line-height: 2.5rem;
`line-height: 2.5rem;` - атата! Не надо так)) сделай полуторный отступ. и не запаривайся

2019-04-16 18:08 UTC, yamnyk commented on src/scss/sections/_footer.scss
> +      font-weight: bold;
обговорил с заказчиком - тут должен быть 400

2019-04-16 18:11 UTC, yamnyk commented on src/index.html
> +                    <p class="contacts__location__address__paragraph">г. Киев, пр. Павла Тычины, 1в,ТОЦ Silver Breeze,офис А, 6-й этаж</p>
тут все таки важно чтобы на первой строке было все ДО слова ТОЦ, остальное на следующей и третьей строки как бы и не надо получается. 
нужно попробовать сделать следующим образом..
каждую строку завернуть в спан и родительскому абзацу флексами прокинуть разположение с колонку

2019-04-16 18:12 UTC, yamnyk commented on src/index.html
> +                <div class="contacts__navigation__cover__social__fb"><img src="img/facebook-footer-icon.png" alt="not-found"></div>
у меня тупо нет твоей папки с картинками...она не прикрепилась к вершн контролю....((

2019-04-16 18:13 UTC, yamnyk commented on src/index.html
> +                <li class="contacts__navigation__cover__menu__item">о нас</li>
тут внутри лишек должны быть ссылки, так как это ж якорные ссылки на странице.

2019-04-16 18:15 UTC, yamnyk commented on src/scss/sections/_footer.scss
> +        display: flex;
вообще это плохим тоном считается просто кинуть флексы и все...в таком случае это считается немного избыточным...прокинь им инлайн блок с отступами тогда просто и все, зачем усложнять))

2019-04-16 18:16 UTC, yamnyk commented on src/index.html
> +                <div class="contacts__navigation__cover__social__inst"><img src="img/instagram-footer-icon.png" alt="not-found"></div>
и вообще заворачивать каждоую картинку в отдельный дивак не обязательно ж...они себе чудесно сосуществуют и без лишних оберток. Убирай вложенность!

2019-04-16 18:17 UTC, yamnyk requested changes
Нужно порефактрить, есть пара косяков. Нужно разобраться с картинками и добавить к контролю версий папку с ними.
Завтра 17.04.2019 буду на месте с 11 утра - приходи дергай меня.

2019-04-17 11:40 UTC, yamnyk commented on src/index.html
>              <div class="contacts__location__address">
в 24 строке от вложенности не избавился

2019-04-17 11:43 UTC, yamnyk requested changes
исправь вложенность

2019-04-17 12:15 UTC, yamnyk approved these changes

2019-04-17 12:18 UTC, Zaitsev-Aleksandr approved these changes

2019-04-17 12:18 UTC, merged